### ISSUE TITLE
Have trouble in Metrics execution

### ISSUE THREAD

**Issue by amanvidura** [Lab41/Circulo#71]
Am a newbie here. I'm currently exploring various community discovery algorithms using Circulo. I'm getting an error message while running the metrics script. Please help me resolve this issue.

Dataset : karate

Error message:
###### Running metrics against karate--conga--0
max() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "run_metrics.py", line 131, in analyze_json
    results_cover.compute_metrics(weights=weights, ground_truth_cover=ground_truth_cover )
  File "/home/user/circulo/circulo/metrics/cover.py", line 276, in compute_metrics
    max_out_results = maximum_out_degree_fraction(cover, odf=odf, weights=weights)
  File "/home/user/circulo/circulo/metrics/cover.py", line 160, in maximum_out_degree_fraction
    max_seen = odf.max(0).tocsc()
TypeError: max() takes 1 positional argument but 2 were given

Thanks!
Aman.

**Comment by Lab41PaulM** [comment]
You are using Python 3, correct? Can you confirm that you are using the latest version of Circulo?   Can you try using the "fastgreedy" algo rather than conga, just to make sure it is not related to the conga output?

**Comment by sqszsqsz** [comment]
Same thing happens here. I'm using the latest Python 3 and latest version of Circulo. It happens for all the algorithms.

**Comment by Jaystings** [comment]
I had the same problem until I commented out the suspect lines.
